name: Selenium with TestNG - CI

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Build with Maven
        run: mvn -B clean test
          
          # Conditional email notification
      - name: Send email if Test fails or skips
        if: failure() || steps.maven.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # Replace with your SMTP server
          server_port: 587
          username: lifeumr@gmail.com # Replace with sender's email
          password: ${{ secrets.SMTP_PASSWORD }} # Use GitHub Secrets for secure credentials
          subject: "AHIMMS90 Website not found on given URL"
          body: |
            There is a problem in the server.Please fixed it now.The Test on ${{ github.ref_name }} branch have failed or been skipped.
            This url not work "http://ahimms90.com/".     
            Details:
            - Repository: ${{ github.repository }}
            - Branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
            - Commit Message: ${{ github.event.head_commit.message }}

          from: lifeumr@gmail.com  # Replace with sender email(s)
          to: srana@ael-bd.com, test.umr007@gmail.com # Replace with recipient email(s)