name: Run Maven Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-maven-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Install Microsoft Edge Browser (required for Selenium)
      - name: Install Microsoft Edge
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable
          microsoft-edge --version

#      # Step 4: Install EdgeDriver with fallback
#      - name: Install EdgeDriver
#        run: |
#          EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+')
#          echo "Edge version: $EDGE_VERSION"
#          EDGE_DRIVER_URL="https://msedgedriver.azureedge.net/${EDGE_VERSION}/edgedriver_linux64.zip"
#
#          # Try to download the driver
#          wget $EDGE_DRIVER_URL -O edgedriver_linux64.zip || (
#            echo "Driver version not found. Falling back to a known working version...";
#            wget https://msedgedriver.azureedge.net/$EDGE_VERSION/edgedriver_linux64.zip -O edgedriver_linux64.zip
#          )
#          unzip edgedriver_linux64.zip -d /usr/local/bin/
#          mv /usr/local/bin/msedgedriver /usr/local/bin/edgedriver
#          edgedriver --version

      # Step 5: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 6: Run Maven commands
      - name: Build and Run Tests
        run: |
          mvn clean install
          mvn test
